<?php

namespace DoctrineORMModule\Proxy\__CG__\Api\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class OauthKey extends \Api\Entity\OauthKey implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setConsumerKey($consumerKey)
    {
        $this->__load();
        return parent::setConsumerKey($consumerKey);
    }

    public function getConsumerKey()
    {
        $this->__load();
        return parent::getConsumerKey();
    }

    public function setConsumerSecret($consumerSecret)
    {
        $this->__load();
        return parent::setConsumerSecret($consumerSecret);
    }

    public function getConsumerSecret()
    {
        $this->__load();
        return parent::getConsumerSecret();
    }

    public function setExpiry($expiry)
    {
        $this->__load();
        return parent::setExpiry($expiry);
    }

    public function getExpiry()
    {
        $this->__load();
        return parent::getExpiry();
    }

    public function setCreatedAt($createdAt)
    {
        $this->__load();
        return parent::setCreatedAt($createdAt);
    }

    public function getCreatedAt()
    {
        $this->__load();
        return parent::getCreatedAt();
    }

    public function addOauthToken(\Api\Entity\OauthToken $oauthTokens)
    {
        $this->__load();
        return parent::addOauthToken($oauthTokens);
    }

    public function removeOauthToken(\Api\Entity\OauthToken $oauthTokens)
    {
        $this->__load();
        return parent::removeOauthToken($oauthTokens);
    }

    public function getOauthTokens()
    {
        $this->__load();
        return parent::getOauthTokens();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'consumerKey', 'consumerSecret', 'expiry', 'createdAt', 'oauthTokens');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}