<?php

namespace Api\Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * GoalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GoalRepository extends EntityRepository {

    public function findUserGoal($goalId, $userId) {
        $qb = $this->createQueryBuilder('g')
                ->innerJoin('g.owner', 'u1')
                ->where('g.id = :goalId')
                ->andWhere('u1.id = :userId')
                ->setParameters(array('goalId' => $goalId, 'userId' => $userId));
        $query = $qb->getQuery();
        if (!$result = $query->getResult()) {
            return false;
        }

        return $result[0];
    }

}
