<?php

namespace Api\Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * GoalCommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GoalCommentRepository extends EntityRepository
{
}
