<?php

namespace Api\Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * OauthKeyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OauthKeyRepository extends EntityRepository
{
}
