<?php

namespace Api\Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * SocialProviderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SocialProviderRepository extends EntityRepository
{
}
