<?php

namespace Api\Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * TaskCommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskCommentRepository extends EntityRepository
{
}
